// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SlackConfig struct {
	Apikey  string `json:"apikey"`
	Channel string `json:"channel"`
}

type ZendeskConfig struct {
	User   string `json:"user"`
	Apikey string `json:"apikey"`
	URL    string `json:"url"`
}
